apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ .Release.Namespace | replace "_" "-" }}
data:
  enabled_plugins: |
    [rabbitmq_federation, rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_mqtt,rabbitmq_web_mqtt, rabbitmq_stream, rabbitmq_stream_management].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.only_log_warning = true

    # Logs and management
    log.console = true
    log.console.level = debug
    log.default.level = debug
    log.connection.level = info
    
    default_user = {{ .Values.RABBITMQ.username }}
    default_pass = {{ .Values.RABBITMQ.password }}
    
    mqtt.exchange = amq.topic
    mqtt.max_session_expiry_interval_seconds = 1800000
    mqtt.prefetch = 10

    ##cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
    ##cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-0.rabbitmq.{{ .Release.Namespace | replace "_" "-" }}.svc.cluster.local
    ##cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-1.rabbitmq.{{ .Release.Namespace | replace "_" "-" }}.svc.cluster.local
    ##cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq-2.rabbitmq.{{ .Release.Namespace | replace "_" "-" }}.svc.cluster.local
