apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocketbase-helm.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
spec:
  selector:
    app: {{ include "pocketbase-helm.fullname" . }}
  type: ClusterIP
  ports:
    - name: pocketbase-port
      port: 8090
      protocol: TCP
      targetPort: 8090
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8090
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8090
