apiVersion: v1
data:
  .dockerconfigjson: '*********************************'
kind: Secret
metadata:
  creationTimestamp: "2023-01-16T16:11:50Z"
  name: githubkubernetes
  namespace: {{ .Release.Namespace | replace "_" "-" }}
type: kubernetes.io/dockerconfigjson
