{{- if eq .Values.INFRASTRUCTURE "gcp" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-ssd-storage-{{ .Release.Namespace | replace "_" "-"}}
  namespace: {{ .Release.Namespace | replace "_" "-"}}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
{{- end }}