apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: {{ .Release.Namespace | replace "_" "-" }}
type: Opaque
data:
  username: {{ .Values.MONGODB.MONGO_ROOT_USERNAME | b64enc | quote }}
  password: {{ .Values.MONGODB.MONGO_ROOT_PASSWORD | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-ssl
  namespace: {{ .Release.Namespace | replace "_" "-" }}
type: Opaque
data:
  ca.pem: {{ .Values.MONGODB.ssl_ca_pem }}
  node.pem: {{ .Values.MONGODB.ssl_member_pem }}
  client.pem: {{ .Values.MONGODB.ssl_client_pem }}