{{- if eq $.Values.INFRASTRUCTURE "gcp" }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: {{ .Values.NAMESPACE | replace "_" "-"}}
spec:
  domains:
    - {{ .Values.MONITOR.BASE_URL }}
{{- end }}