apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: {{ .Values.NAMESPACE | replace "_" "-" }}
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.external-url=https://monitor.service.upswing.global/prometheus/"
            - "--log.level=debug"
          ports:
            - name: http-prometheus
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: prometheus-data-dir
              mountPath: /prometheus
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-data-dir
          persistentVolumeClaim:
            claimName: prometheus-data-dir
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-dir
  namespace: {{ .Values.NAMESPACE | replace "_" "-" }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "monitor-ssd-storage-{{ .Values.NAMESPACE | replace "_" "-" }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
